allow unions to roundtrip without errors
If a union contains a type T, when decoding into a struct field of said
union type, we would end up with a value of type *T.

This is fine for Unmarshal itself. However, Marshal errors when it
encounters *T instead of T for that union, because the ut.tags map does
not contain *T.

Teach it to reach past the pointer if it encounters *T instead of T, so
that it can encode the type T. Add a simple test round-tripping what's
explained above, which fails without the fix:

	marshal_test.go:274:
		Error Trace: marshal_test.go:274
		Error:       Expected nil, but got: &errors.errorString{s:"Invalid union value: <*bare.Age Value>"}
		Test:        TestRoundtrip